#!/bin/sh

if [ "$#" -ne  1 ]; then
  echo "Usage $0 [main_cpp_file]"
  exit 1
fi

BASEDIR=$(dirname "$0")
COMPILED_FILES_DIR="${BASEDIR}/compiledFiles"

MAIN_FILE_PATH=$(realpath "$1")
OUTPUT_FILE_PATH=${MAIN_FILE_PATH%.*}

echo "Compiling..."
g++ -o ${OUTPUT_FILE_PATH} ${MAIN_FILE_PATH} ${COMPILED_FILES_DIR}/MuUtil.o ${COMPILED_FILES_DIR}/MuError.o ${COMPILED_FILES_DIR}/MuParamBlock.o ${COMPILED_FILES_DIR}/MuNote.o ${COMPILED_FILES_DIR}/MuVoice.o ${COMPILED_FILES_DIR}/MuMaterial.o -I ${BASEDIR}

chmod 755 ${OUTPUT_FILE_PATH}

echo ""
echo "Executable file:"
echo "${OUTPUT_FILE_PATH}"
